### ISSUE TITLE
插件报错

### ISSUE THREAD

**Issue by ABKQPO** [lgc-NB2Dev/nonebot-plugin-eitherchoice#2]
```pytb
Traceback (most recent call last):
  File "D:\NoneBot\ABK\bot.py", line 21, in <module>
    nonebot.run()
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
    uvicorn.run(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\uvicorn\main.py", line 578, in run
    server.run()
  File "D:\NoneBot\ABK\.venv\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\message.py", line 467, in check_and_run_matcher
    await _run_matcher(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\message.py", line 419, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 728, in simple_run
    await handler(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_eitherchoice\__main__.py", line 42, in _
    pic = await get_choice_pic(*things)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_eitherchoice\data_source.py", line 139, in get_choice_pic
    return await render_image(thing_a, thing_b, await get_choice_all(thing_a, thing_b))
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_eitherchoice\data_source.py", line 134, in get_choice_all
    return await get_choice_all(thing_a, thing_b, retry, referer)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_eitherchoice\data_source.py", line 128, in get_choice_all
    return "".join([i async for i in get_choice_stream(thing_a, thing_b, referer)])
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_eitherchoice\data_source.py", line 128, in <listcomp>
    return "".join([i async for i in get_choice_stream(thing_a, thing_b, referer)])
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_eitherchoice\data_source.py", line 106, in get_choice_stream
    async with client.stream(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_client.py", line 1573, in stream
    response = await self.send(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\_async\connection_pool.py", line 253, in handle_async_request
    raise exc
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\_async\socks_proxy.py", line 290, in handle_async_request
    raise exc
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\_async\socks_proxy.py", line 238, in handle_async_request
    await _init_socks5_connection(**kwargs)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\_async\socks_proxy.py", line 93, in _init_socks5_connection
    response = conn.receive_data(incoming_bytes)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\socksio\socks5.py", line 382, in receive_data
    reply = SOCKS5Reply.loads(data)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\socksio\socks5.py", line 262, in loads
    addr=decode_address(AddressType.from_socks5_atype(atype), data[4:-2]),
TypeError: unhashable type: 'bytearray'
```

**Comment by lgc2333** [comment]
试试使用http代理

**Comment by lgc2333** [comment]
我这边找到了一个关于这个问题的 Discussion https://github.com/encode/httpx/discussions/2305

**Comment by ABKQPO** [comment]
使用http://127.0.0.1:7890也会报错

**Comment by lgc2333** [comment]
可以给下报错内容吗

**Comment by ABKQPO** [comment]
```pytb
06-30 21:57:03 [INFO] nonebot_plugin_eitherchoice | Referer: https://eitherchoice.com/fighting/%E5%8E%9F%E7%A5%9E-vs-%E5%A1%9E%E5%B0%94%E8%BE%BE%E4%BC%A0%E8%AF%B4%EF%BC%9A%E7%8E%8B%E5%9B%BD%E4%B9%8B%E6%B3%AA?t=1688133423536&p=true
06-30 21:57:03 [WARNING] nonebot_plugin_eitherchoice | Failed to get choice, retrying (1 left)
Traceback (most recent call last):
  File "D:\NoneBot\ABK\bot.py", line 21, in <module>
    nonebot.run()
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
    uvicorn.run(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\uvicorn\main.py", line 578, in run
    server.run()
  File "D:\NoneBot\ABK\.venv\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\message.py", line 467, in check_and_run_matcher
    await _run_matcher(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\message.py", line 419, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 728, in simple_run
    await handler(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_eitherchoice\__main__.py", line 54, in _
    pic = await get_choice_pic(*things)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_eitherchoice\data_source.py", line 139, in get_choice_pic
    return await render_image(thing_a, thing_b, await get_choice_all(thing_a, thing_b))
> File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_eitherchoice\data_source.py", line 128, in get_choice_all
    return "".join([i async for i in get_choice_stream(thing_a, thing_b, referer)])
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_eitherchoice\data_source.py", line 128, in <listcomp>
    return "".join([i async for i in get_choice_stream(thing_a, thing_b, referer)])
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_eitherchoice\data_source.py", line 106, in get_choice_stream
    async with client.stream(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_client.py", line 1573, in stream
    response = await self.send(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\_async\connection_pool.py", line 253, in handle_async_request
    raise exc
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\_async\socks_proxy.py", line 290, in handle_async_request
    raise exc
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\_async\socks_proxy.py", line 238, in handle_async_request
    await _init_socks5_connection(**kwargs)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\_async\socks_proxy.py", line 93, in _init_socks5_connection
    response = conn.receive_data(incoming_bytes)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\socksio\socks5.py", line 382, in receive_data
    reply = SOCKS5Reply.loads(data)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\socksio\socks5.py", line 262, in loads
    addr=decode_address(AddressType.from_socks5_atype(atype), data[4:-2]),
TypeError: unhashable type: 'bytearray'
06-30 21:57:03 [INFO] nonebot_plugin_eitherchoice | Referer: https://eitherchoice.com/fighting/%E5%8E%9F%E7%A5%9E-vs-%E5%A1%9E%E5%B0%94%E8%BE%BE%E4%BC%A0%E8%AF%B4%EF%BC%9A%E7%8E%8B%E5%9B%BD%E4%B9%8B%E6%B3%AA?t=1688133423536&p=true
06-30 21:57:03 [ERROR] nonebot_plugin_eitherchoice | 发生错误
Traceback (most recent call last):
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_eitherchoice\data_source.py", line 128, in get_choice_all
    return "".join([i async for i in get_choice_stream(thing_a, thing_b, referer)])
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_eitherchoice\data_source.py", line 128, in <listcomp>
    return "".join([i async for i in get_choice_stream(thing_a, thing_b, referer)])
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_eitherchoice\data_source.py", line 106, in get_choice_stream
    async with client.stream(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_client.py", line 1573, in stream
    response = await self.send(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\_async\connection_pool.py", line 253, in handle_async_request
    raise exc
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\_async\socks_proxy.py", line 290, in handle_async_request
    raise exc
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\_async\socks_proxy.py", line 238, in handle_async_request
    await _init_socks5_connection(**kwargs)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\_async\socks_proxy.py", line 93, in _init_socks5_connection
    response = conn.receive_data(incoming_bytes)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\socksio\socks5.py", line 382, in receive_data
    reply = SOCKS5Reply.loads(data)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\socksio\socks5.py", line 262, in loads
    addr=decode_address(AddressType.from_socks5_atype(atype), data[4:-2]),
TypeError: unhashable type: 'bytearray'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\NoneBot\ABK\bot.py", line 21, in <module>
    nonebot.run()
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
    uvicorn.run(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\uvicorn\main.py", line 578, in run
    server.run()
  File "D:\NoneBot\ABK\.venv\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\message.py", line 467, in check_and_run_matcher
    await _run_matcher(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\message.py", line 419, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 728, in simple_run
    await handler(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_eitherchoice\__main__.py", line 54, in _
    pic = await get_choice_pic(*things)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_eitherchoice\data_source.py", line 139, in get_choice_pic
    return await render_image(thing_a, thing_b, await get_choice_all(thing_a, thing_b))
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_eitherchoice\data_source.py", line 134, in get_choice_all
    return await get_choice_all(thing_a, thing_b, retry, referer)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_eitherchoice\data_source.py", line 128, in get_choice_all
    return "".join([i async for i in get_choice_stream(thing_a, thing_b, referer)])
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_eitherchoice\data_source.py", line 128, in <listcomp>
    return "".join([i async for i in get_choice_stream(thing_a, thing_b, referer)])
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_eitherchoice\data_source.py", line 106, in get_choice_stream
    async with client.stream(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_client.py", line 1573, in stream
    response = await self.send(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\_async\connection_pool.py", line 253, in handle_async_request
    raise exc
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\_async\socks_proxy.py", line 290, in handle_async_request
    raise exc
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\_async\socks_proxy.py", line 238, in handle_async_request
    await _init_socks5_connection(**kwargs)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\_async\socks_proxy.py", line 93, in _init_socks5_connection
    response = conn.receive_data(incoming_bytes)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\socksio\socks5.py", line 382, in receive_data
    reply = SOCKS5Reply.loads(data)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\socksio\socks5.py", line 262, in loads
    addr=decode_address(AddressType.from_socks5_atype(atype), data[4:-2]),
TypeError: unhashable type: 'bytearray'
06-30 21:57:04 [ERROR] nonebot_plugin_eitherchoice | 如果多次发生 Server disconnected 错误，请尝试增加 retry 次数
```

**Comment by lgc2333** [comment]
怪了，真没见过……………
